# Generated by Django 3.1.1 on 2020-10-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date',
                 models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
