# Generated by Django 3.1.1 on 2020-10-02 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='volume',
            table='volume',
        ),
    ]
