# Generated by Django 3.1.2 on 2020-10-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_rename_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='volume',
            name='available',
            field=models.BooleanField(default=False,
                                      verbose_name='available online'),
        ),
        migrations.AddField(
            model_name='volume',
            name='dateBegin',
            field=models.DateField(default=None,
                                   verbose_name='beginning date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='dateEnd',
            field=models.DateField(default=None, verbose_name='ending date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volume',
            name='pages',
            field=models.BigIntegerField(default=None,
                                         verbose_name='number of pages'),
            preserve_default=False,
        ),
    ]
