# Generated by Django 3.1.2 on 2020-10-06 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_volume_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='title',
            new_name='name',
        ),
    ]
