# Generated by Django 3.1.2 on 2020-10-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_volume_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateAdded', models.DateField(verbose_name='added on date')),
                ('dateUpdated', models.DateField(verbose_name='updated on date')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
