# Generated by Django 3.1.2 on 2020-10-07 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_added_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(verbose_name='page number')),
                ('date', models.DateField(verbose_name='date of mention')),
                ('year', models.IntegerField(verbose_name='year of mention')),
                ('itemId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemPages', to='main.item')),
                ('volumeId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='volumeItemPages', to='main.item')),
            ],
            options={
                'db_table': 'item_page',
            },
        ),
    ]
