# Generated by Django 3.1.2 on 2020-10-07 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_itempage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempage',
            name='volumeId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='volumeItemPages', to='main.volume'),
        ),
    ]
