# Generated by Django 3.1.2 on 2020-10-08 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_itempage_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'note_type',
            },
        ),
        migrations.CreateModel(
            name='TopicNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('relatedTopicId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='topicNoteRelatedTopic', to='main.topic')),
                ('topicId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='noteTopic', to='main.topic')),
                ('typeId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='topicNotes', to='main.notetype')),
            ],
            options={
                'db_table': 'topic_note',
            },
        ),
        migrations.CreateModel(
            name='ItemNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('itemId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='noteItem', to='main.item')),
                ('relatedTopicId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemNoteRelatedTopic', to='main.topic')),
                ('typeId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemNotes', to='main.notetype')),
            ],
            options={
                'db_table': 'item_note',
            },
        ),
    ]
