# Generated by Django 3.1.2 on 2020-10-08 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_note_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libraryNum', models.CharField(max_length=200, verbose_name='library call number')),
                ('page', models.CharField(max_length=20, verbose_name='page number')),
                ('imageNumber', models.IntegerField(verbose_name='image number')),
                ('confidence', models.IntegerField(verbose_name='scan quality confidence')),
                ('pageType', models.CharField(max_length=20, verbose_name='page content type')),
                ('volumeId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='volume_page_mapping', to='main.volume')),
            ],
            options={
                'db_table': 'page_mapping',
            },
        ),
    ]
