# Generated by Django 3.1.2 on 2020-10-08 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0011_pagemapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='name',
            new_name='title',
        ),
    ]
