# Generated by Django 3.1.2 on 2020-10-10 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0012_volume_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicnote',
            name='relatedTopicId',
            field=models.OneToOneField(null=True,
                                       on_delete=django.db.models.deletion.DO_NOTHING,
                                       related_name='topicNoteRelatedTopic',
                                       to='main.topic'),
        ),
    ]
