# Generated by Django 3.1.2 on 2020-10-10 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0013_topicnote_relatedtopic_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicnote',
            name='relatedTopicId',
            field=models.OneToOneField(blank=True, null=True,
                                       on_delete=django.db.models.deletion.DO_NOTHING,
                                       related_name='topicNoteRelatedTopic',
                                       to='main.topic'),
        ),
    ]
