# Generated by Django 3.1.2 on 2020-10-13 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0014_topicnote_relatedtopic_blankable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicnote',
            name='typeId',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='topicNotes', to='main.notetype'),
        ),
    ]
