# Generated by Django 3.1.2 on 2020-10-13 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_topicnote_topic_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='topicId',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='itemnote',
            old_name='itemId',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='itemnote',
            old_name='relatedTopicId',
            new_name='relatedTopic',
        ),
        migrations.RenameField(
            model_name='itemnote',
            old_name='typeId',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='itempage',
            old_name='itemId',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='itempage',
            old_name='volumeId',
            new_name='volume',
        ),
        migrations.RenameField(
            model_name='pagemapping',
            old_name='volumeId',
            new_name='volume',
        ),
        migrations.RenameField(
            model_name='topicnote',
            old_name='relatedTopicId',
            new_name='relatedTopic',
        ),
        migrations.RenameField(
            model_name='topicnote',
            old_name='topicId',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topicnote',
            old_name='typeId',
            new_name='type',
        ),
    ]
