# Generated by Django 3.1.2 on 2020-10-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_column_id_suffixes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemnote',
            name='relatedTopic',
        ),
        migrations.RemoveField(
            model_name='topicnote',
            name='relatedTopic',
        ),
        migrations.AddField(
            model_name='itemnote',
            name='referencedTopic',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemNoteReferencedTopic', to='main.topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicnote',
            name='referencedTopic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topicNoteReferencedTopic', to='main.topic'),
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='noteItem', to='main.item'),
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemNotes', to='main.notetype'),
        ),
    ]
