# Generated by Django 3.1.2 on 2020-10-13 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0018_rename_topic_fks__itemnote_fk_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='topic',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='items', to='main.topic'),
        ),
    ]
