# Generated by Django 3.1.2 on 2020-10-22 19:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0020_no_more_onetoone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='dateAdded',
            field=models.DateField(default=datetime.date.today,
                                   verbose_name='added on date'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='dateUpdated',
            field=models.DateField(default=datetime.date.today,
                                   verbose_name='updated on date'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
