# Generated by Django 3.1.2 on 2020-10-23 02:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_topic_defaults_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateAdded',
            field=models.DateField(default=datetime.date.today, verbose_name='added on date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateUpdated',
            field=models.DateField(default=datetime.date.today, verbose_name='updated on date'),
        ),
        migrations.AlterField(
            model_name='itempage',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='volumeItemPages', to='main.volume'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'topic'), name='topic_item'),
        ),
    ]
