# Generated by Django 3.1.2 on 2020-10-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0022_item_itempage_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempage',
            name='date',
            field=models.DateField(null=True, verbose_name='date of mention'),
        ),
    ]
