# Generated by Django 3.1.2 on 2020-10-27 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0023_itempage_date_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dateUpdated',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='dateUpdated',
        ),
        migrations.AddField(
            model_name='item',
            name='addedTime',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updatedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='addedTime',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='updatedTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
