# Generated by Django 3.1.2 on 2020-10-27 19:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0024_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempage',
            name='month',
        ),
        migrations.RemoveField(
            model_name='itempage',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='itempage',
            name='year',
        ),
        migrations.AlterField(
            model_name='itempage',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True,
                                   verbose_name='date of mention'),
        ),
    ]
