# Generated by Django 3.1.2 on 2020-10-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0025_itempage_column_removals'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempage',
            name='month',
            field=models.IntegerField(
                choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'),
                         (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'),
                         (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')],
                null=True, verbose_name='month of mention'),
        ),
        migrations.AddField(
            model_name='itempage',
            name='year',
            field=models.IntegerField(default=None,
                                      verbose_name='year of mention'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempage',
            name='date',
            field=models.DateField(null=True, verbose_name='date of mention'),
        ),
    ]
