# Generated by Django 3.1.7 on 2021-03-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0026_revert_date_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='addedTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='updatedTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='addedTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updatedTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
