# Generated by Django 3.2 on 2021-04-09 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0027_allow_null_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='referencedTopic',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='itemNoteReferencedTopic',
                to='main.topic'),
        ),
    ]
