# Generated by Django 3.2 on 2021-04-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0028_ItemNote_referencedTopic_nullable_blankable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='topicnote',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
