# Generated by Django 3.2 on 2021-04-12 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0029_note_text_nullable_blankable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='topic_item',
        ),
    ]
