# Generated by Django 3.2 on 2021-04-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_longer_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempage',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='volumeItemPages', to='main.volume'),
        ),
    ]
