# Generated by Django 3.2 on 2021-04-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_itempage_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempage',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year of mention'),
        ),
    ]
