# Generated by Django 3.2 on 2021-04-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0033_allow_itempage_year_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemapping',
            name='volume',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='pageMappings', to='main.volume'),
        ),
        migrations.AlterField(
            model_name='topicnote',
            name='referencedTopic',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='topicNoteReferences',
                                    to='main.topic'),
        ),
        migrations.AlterField(
            model_name='topicnote',
            name='topic',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='topicNotes', to='main.topic'),
        ),
        migrations.AlterField(
            model_name='topicnote',
            name='type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='typeNotes', to='main.notetype'),
        ),
    ]
