# Generated by Django 3.2 on 2021-04-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_model_relationship_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempage',
            name='page',
            field=models.CharField(max_length=20, verbose_name='page number'),
        ),
    ]
