# Generated by Django 3.2 on 2021-04-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_itempage_page_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnote',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemNotes', to='main.item'),
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='referencedTopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemNoteReferences', to='main.topic'),
        ),
        migrations.AlterField(
            model_name='itemnote',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemNotes', to='main.notetype'),
        ),
        migrations.AlterField(
            model_name='topicnote',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topicNotes', to='main.notetype'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='pages',
            field=models.BigIntegerField(verbose_name='total number of pages'),
        ),
    ]
