# Generated by Django 3.2 on 2021-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0036_update_note_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='libraryNum',
            field=models.CharField(default='acw7513.____.001', max_length=200,
                                   verbose_name='library call number'),
            preserve_default=False,
        ),
    ]
