# Generated by Django 3.2 on 2021-04-24 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_volume_librarynum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemapping',
            name='libraryNum',
        ),
    ]
