# Generated by Django 3.2.3 on 2021-05-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0039_add_explicit_id_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempage',
            name='date',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='date of mention'),
        ),
        migrations.AlterField(
            model_name='itempage',
            name='month',
            field=models.IntegerField(blank=True,
                                      choices=[(1, 'Jan'), (2, 'Feb'),
                                               (3, 'Mar'), (4, 'Apr'),
                                               (5, 'May'), (6, 'Jun'),
                                               (7, 'Jul'), (8, 'Aug'),
                                               (9, 'Sep'), (10, 'Oct'),
                                               (11, 'Nov'), (12, 'Dec')],
                                      null=True,
                                      verbose_name='month of mention'),
        ),
    ]
