# Generated by Django 4.2.24 on 2025-11-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0040_itempage_blank_date_and_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempage',
            name='page',
            field=models.IntegerField(verbose_name='page number'),
        ),
    ]
